modLoader="javafml"
loaderVersion="*"
issueTrackerURL="https://github.com/UltimatChamp/ModpackUtils/issues"
displayURL="https://github.com/UltimatChamp/ModpackUtils"
logoFile="assets/mutils/icon.png"
authors="${mod_authors}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''

[[dependencies.mutils]]
modId="neoforge"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.mutils]]
modId="minecraft"
type="required"
versionRange="${minecraft_range}"
ordering="NONE"
side="BOTH"

[[dependencies.mutils]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="*"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="mutils.mixins.json"
